import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const aeonik = localFont({
  variable: "--aeonik-font",
  src: [
    {
      path: "./fonts/Aeonik/Aeonik-Bold.otf",
      weight: "700",
    },
    {
      path: "./fonts/Aeonik/Aeonik-Medium.otf",
      weight: "600",
    },
    {
      path: "./fonts/Aeonik/Aeonik-Regular.otf",
      weight: "500",
    },
    {
      path: "./fonts/Aeonik/Aeonik-Thin.otf",
      weight: "300",
    },
  ],
});

const polySans = localFont({
  variable: "--polySans-font",
  src: [
    {
      path: "./fonts/PolySansMedian/PolySansMedian.ttf",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${polySans.variable} ${aeonik.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
